
name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn

      - name: Run Build
        run: yarn build
        
      - name: Copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ".,!node_modules"
          target: "~/app/rocketlab-backend"
          
          
      - name: Install dependencies on Digital Ocean and Execute Migration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/rocketlab-backend
            yarn build
            yarn
             ./node_modules/.bin/typeorm migration:run
             pm2 restart xplab-api
            


            
            
